language: go
go:
  - "1.11.x"
  - "tip"

env:
  - GO111MODULE=on GOROOT=/usr/local/go

before_script:
  - mkdir -p $GOPATH/bin
  - make deps

matrix:
  allow_failures:
    - go: tip

script:
  - go vet $(go list ./... | grep -v /vendor/)
  - go test $(go list ./... | grep -v /vendor/)
  - make
